server:
  port: 18088

spring:
  datasource:
    name: wzs
    url: jdbc:mysql://localhost:33006/vhr?useUnicode=true&characterEncoding=utf8
    username: root
    password: haojiwei
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wzs.mapper

mapper:
  mappers:  com.wzs.mapper
  not-empty: false
  identity: MYSQL