server:
  port: 18088

spring:
  datasource:
    name: wzs
    url: jdbc:mysql://localhost:33006/wzs?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: haojiwei
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.126.com
    username: microknowledge@126.com
    password: LULPPGHPUWMQROFR
    properties:
      mail:
       smtp:
         ssl:
          enable: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wzs.mapper

mapper:
  mappers:  com.wzs.mapper
  not-empty: false
  identity: MYSQL

